---
collections:
- name: community.general
- name: containers.podman
- name: infra.ee_utilities
- name: hfenner.aap_utilities
  source: https://github.com/hfenner/aap_utilities.git
  version: devel
  type: git
