---
- name: Remove the functional Realm
  k8s:
    api_key: "{{ openshift_auth_results.k8s_auth.api_key }}"
    host: "{{ managed_cluster_server }}"
    validate_certs: no
    state: absent
    name: openshift-realm
    kind: KeycloakRealm
    api_version: keycloak.org/v1alpha1
    namespace: sso

- name: Allow Realm to be removed from api
  shell:
    cmd: sleep 15 

- name: Create Keycloak Realm - typo in redirectUri
  k8s:
    api_key: "{{ openshift_auth_results.k8s_auth.api_key }}"
    host: "{{ managed_cluster_server }}"
    validate_certs: no
    state: present
    name: openshift-realm
    namespace: sso
    definition:
      kind: KeycloakRealm
      apiVersion: keycloak.org/v1alpha1
      metadata:
        labels:
          app: sso
      spec:
        instanceSelector:
          matchLabels:
            app: sso
        realm:
          clients:
            - enabled: true
              clientAuthenticatorType: client-secret
              redirectUris:
                - >-
                  https://oauth-openshift.apps.{{ managed_cluster_name }}.typo.dev/oauth2callback/rh-sso
              clientId: openshift
              implicitFlowEnabled: false
              secret: "{{ keycloak_client_secret }}"
              publicClient: false
              standardFlowEnabled: true
              directAccessGrantsEnabled: false
          displayName: openshift
          enabled: true
          id: openshift
          identityProviders:
            - alias: github
              config:
                clientId: "{{ oauth_client_id }}"
                clientSecret: "{{ oauth_client_secret }}"
                syncMode: IMPORT
                useJwksUrl: 'true'
              enabled: true
              firstBrokerLoginFlowAlias: first broker login
              providerId: github
          realm: openshift

# - name: Remove kubeadmin secret
#   k8s:
#     api_key: "{{ openshift_auth_results.k8s_auth.api_key }}"
#     host: "{{ managed_cluster_server }}"
#     validate_certs: no
#     state: absent
#     definition:
#       apiVersion: v1
#       kind: Secret
#       metadata:
#         name: kubeadmin
#         namespace: kube-system
#       type: Opaque