---

- hosts: localhost
  module_defaults:
    group/k8s:
      api_key: "{{ acm_hub_service_account }}"
      host: "{{ acm_hub_server }}"
      validate_certs: no
  tasks:  
    - import_role: 
        name: roles/acm_managed_cluster_create
      when: cluster_create

    - import_role: 
        name: roles/managed_cluster_login

    - import_role:
        name: roles/cert_manager
      when: cert_manager_config

    - import_role: 
        name: roles/rhsso_oauth
      when: sso_config
