---

- hosts: localhost
  module_defaults:
    group/k8s:
      api_key: "{{ acm_hub_service_account }}"
      host: "{{ acm_hub_server }}"
      validate_certs: no
  tasks:  
    - import_role: roles/acm_managed_cluster_create

    - import_role: roles/managed_cluster_login
      when: acm_create | bool

    - import_role: roles/rhsso_oauth
      when: acm_remove | bool
