---

- hosts: localhost
  module_defaults:
    group/k8s:
      api_key: "{{ acm_hub_service_account }}"
      host: "{{ acm_hub_server }}"
      validate_certs: no
  
- import_roles: roles/acm_managed_cluster_create

- import_roles: roles/managed_cluster_login
  when: acm_create | bool

- import_roles: roles/rhsso_oauth
  when: acm_remove | bool
