---
- hosts: all

  tasks:
  - name: Show agent
    command: "ls /runner/artifacts/{{ awx_job_id }}"
    delegate_to: localhost
    
  - name: print all variables
    debug:
      var=vars

  - name: print all variables
    debug:
      var=ansible_ssh_private_key_file
