version: 1
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  append: |
    RUN pip3 install --upgrade pip setuptools
    RUN yum install -y yum-utils
    RUN yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    RUN yum install -y terraform packer vault wget
    RUN wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
    RUN tar xvzf openshift-client-linux.tar.gz
    RUN chmod +x oc
    RUN chmod +x kubectl
    RUN mv kubectl /usr/bin/kubectl
    RUN mv oc /usr/bin/oc
    ENV PATH "/usr/bin:$PATH"
