version: 1
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

ansible_config: 'ansible.cfg'
additional_build_steps:
  append: |
    RUN pip3 install --upgrade pip setuptools; \
        yum install -y yum-utils; \
        yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo; \
        yum install -y terraform packer vault wget; \
        wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz; \
        tar xvzf openshift-client-linux.tar.gz; \
        chmod +x oc; \
        chmod +x kubectl; \
        mv kubectl /usr/bin/kubectl; \
        mv oc /usr/bin/oc
    ENV PATH "/usr/bin:$PATH"
