---
collections:
  - community.okd
  - kubernetes.core
  - community.general
  - amazon.aws
  - vmware.vmware_rest 
  - community.vmware
  - awx.awx
  - community.crypto
  - community.aws
  - ansible.windows
  - ansible.controller
