---
# - name: Template ACM resources 
#   template:
#     src: "acm-cluster-create.yaml.j2"
#     dest: "acm-cluster-create.yaml"

# - name: Template OpenShift install config
#   template:
#     src: "install-config.yaml.j2"
#     dest: "install-config.yaml"

# - name: Create {{ project_name }} namespace
#   kubernetes.core.k8s:
#     api_key: "{{ openshift_service_account }}"
#     host: "{{ openshift_server }}"
#     api_version: project.openshift.io/v1
#     kind: Project
#     name: "{{ cluster_name }}"
#     state: present

# - name: Login with openshift
#   shell:
#     cmd: oc login --token="{{ openshift_service_account }}" --server="{{ openshift_server }}"

# - name: Navigate to ansible-automation-platform namespace
#   shell:
#     cmd: oc project ansible-automation-platform

# - name: Create secret from the install-config template
#   shell:
#     cmd: oc create secret generic {{ cluster_name }}-install-config --from-file=install-config.yaml=install-config.yaml -n "{{ cluster_name }}"

# - name: Create cluster resources for ACM
#   shell:
#     cmd: oc apply -f acm-cluster-create.yaml
      

- name: Install RHSSO Operator
  k8s:
    definition: "{{ lookup('kubernetes.core.kustomize', dir='acm_cluster/files/rhsso-operator/base') }}"  

- name: Create Keycloak Realm
  k8s:
    state: present
    name: openshift-realm
    definition:
      kind: KeycloakRealm
      apiVersion: keycloak.org/v1alpha1
      spec:
        instanceSelector:
          matchLabels:
            app: sso
        realm:
          clients:
            - enabled: true
              clientAuthenticatorType: client-secret
              redirectUris:
                - >-
                  https://oauth-openshift.apps.dirt-hackathon.dragonslair.dev/oauth2callback/myapp
              clientId: openshift
              implicitFlowEnabled: false
              secret: 84f837f9-8567-4ade-9c18-ad90ce856757
              publicClient: false
              standardFlowEnabled: true
              id: 9eae225c-612a-4d20-bffe-c686a3e141e3
              directAccessGrantsEnabled: false
          displayName: openshift
          enabled: true
          id: openshift
          identityProviders:
            - alias: github
              config:
                clientId: 94127f2b163806f210ad
                clientSecret: fc5984081787587a2864ff9e414b4b252741e29d
                syncMode: IMPORT
                useJwksUrl: 'true'
              enabled: true
              firstBrokerLoginFlowAlias: first broker login
              internalId: e4f88909-858c-4a84-a3c3-e28d72528d5b
              providerId: github
          realm: openshift
