---
- hosts: installationserver
  vars:
    work_dir: "{{ playbook_dir }}"
  pre_tasks:
  - name: Populate TLS key and certificate
    ansible.builtin.copy:
      content: "{{ item.content }}"
      mode: "{{ item.mode }}"
      dest: "{{ work_dir }}/{{ item.dest }}"
    loop:
    - content: "{{ aap_platform_key }}"
      mode: '0600'
      dest: aap.dragonslair.dev.pem
    - content: "{{ aap_platform_cert }}"
      mode: '0644'
      dest: aap.dragonslair.dev.crt
    - content: "{{ isrgx1_root_cert }}"
      mode: '0644'
      dest: isrgx1_root_cert.crt
  roles:
  - { role: hfenner.aap_utilities.aap_setup_download }
  - { role: hfenner.aap_utilities.aap_setup_prepare }
  - { role: hfenner.aap_utilities.aap_setup_install }
