---
- hosts: installationserver
  roles:
  - { role: hfenner.aap_utilities.aap_setup_download }
  - { role: hfenner.aap_utilities.aap_setup_prepare }
  - { role: hfenner.aap_utilities.aap_setup_install }
