---
- hosts: installationserver
  pre_tasks:
  - name: Ensure SSH home dir exists
    file:
      path: /home/runner/.ssh
      state: directory
      mode: '0700'

  - name: Copy SSH key to temp
    ansible.builtin.copy:
      content: "{{ machine_key }}" 
      dest: "{{ privatekeypath }}"
      mode: '0600'
  roles:
  - { role: hfenner.aap_utilities.aap_setup_download }
  - { role: hfenner.aap_utilities.aap_setup_prepare }
  - { role: hfenner.aap_utilities.aap_setup_install }
  post_tasks:
  - name: Delete SSH key to temp
    ansible.builtin.file:
      state: absent
      dest: "{{ privatekeypath }}"
