---
apiVersion: v1
stringData:
  clientSecret: "{{ github_oauth_secret }}"
kind: Secret
metadata:
  name: github-secret
  namespace: openshift-config
---
apiVersion: v1
stringData:
  awsSecretAccessKey:  "{{ cert_manager_aws_secret_access_key }}"
kind: Secret
metadata:
  name: aws-secret
  namespace: cert-manager
