---
apiVersion: v1
stringData:
  clientSecret: "{{ github_oauth_secret }}"
kind: Secret
metadata:
  name: github-secret
  namespace: openshift-config
---
apiVersion: v1
stringData:
  awsSecretAccessKey:  "{{ cert_manager_aws_secret_access_key }}"
kind: Secret
metadata:
  name: aws-secret
  namespace: cert-manager
---
apiVersion: v1
stringData:
  appId: "{{ github_group_sync_appid }}"
  privateKey: "{{ github_group_sync_private_key }}"
kind: Secret
metadata:
  name: github-group-sync
  namespace: group-sync-operator
