---
- name: Template ACM resources 
  template:
    src: "acm-cluster-create.yaml.j2"
    dest: "acm-cluster-create.yaml"

- name: Template OpenShift install config
  template:
    src: "install-config.yaml.j2"
    dest: "install-config.yaml"

- name: Create {{ managed_cluster_name }} namespace
  k8s:
    api_version: project.openshift.io/v1
    kind: Project
    name: "{{ managed_cluster_name }}"
    state: present

- name: Login with openshift
  shell:
    cmd: oc login --token="{{ acm_hub_service_account }}" --server="{{ acm_hub_server }}"

# - name: Navigate to ansible-automation-platform namespace
#   shell:
#     cmd: oc project ansible-automation-platform

- name: Create secret from the install-config template
  shell:
    cmd: oc create secret generic {{ managed_cluster_name }}-install-config --from-file=install-config.yaml=install-config.yaml -n "{{ managed_cluster_name }}"

- name: Create cluster resources for ACM
  shell:
    cmd: oc apply -f acm-cluster-create.yaml